version: '2'

services:

  base:
    #build: .
    image: foodjin-customer:latest
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  remove:
    extends:
       service: base
    command: rm -rf node_modules
  install:
    extends:
      service: base
    command: npm i

