apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodjin-customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodjin-customer-service
  template:
    metadata:
      labels:
        app: foodjin-customer-service
    spec:
      containers:
      - name: foodjin-customer-service
        image: acrcustomerservice.azurecr.io/foodjin-customer-service:latest
        ports:
        - containerPort: 5014
---
apiVersion: v1
kind: Service
metadata:
  name: foodjin-customer-service
spec:
  type: ClusterIP
  ports:
  - port: 5014
  selector:
    app: foodjin-customer-service