-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgD1egn2fkolujHzrVK0ChmTomryayxh77eKiihOg8a0GgCgYIKoZIzj0DAQehRANCAASQwg5sTrlKprAmpm8TYWQGGA2IED4ih+1w+ALlx+i3kI7bRLKVwW3t/uq+TRUoU3ZDuxiqxujMqz3e7N6G/BM2
-----END PRIVATE KEY-----